- name: install systemd-journal-remote
  apt:
    name: systemd-journal-remote
    state: present


- name: enforce permissions of /var/log/journal/remote/
  file:
    state: directory
    path: /var/log/journal/remote/
    owner: systemd-journal-remote
    group: systemd-journal-remote
    mode: 0750

- name: template /etc/systemd/journal-remote.conf
  template:
    src: templates/etc/systemd/journal-remote.conf.j2
    dest: /etc/systemd/journal-remote.conf
    owner: systemd-journal-remote
    group: systemd-journal-remote
    mode: 0640
  notify:
    - reload systemd daemon
    - restart systemd-journal-remote.socket
    - restart systemd-journal-remote.service

- name: template /etc/systemd/system/systemd-journal-remote.service.j2
  template:
    src: templates/etc/systemd/system/systemd-journal-remote.service.j2
    dest: /etc/systemd/system/systemd-journal-remote.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd daemon
    - restart systemd-journal-remote.socket
    - restart systemd-journal-remote.service
