- name: reload systemd daemon
  systemd:
    daemon_reload: True

- name: restart systemd-journal-remote.service
  systemd:
    name: systemd-journal-remote.service
    state: restarted
    enabled: True

- name: restart systemd-journal-remote.socket
  systemd:
    name: systemd-journal-remote.socket
    state: restarted
    enabled: True
